// Generated by scripts/media-manifest.mjs from public/media. Do not edit by hand.
// Add a photo named after its slot id (hero_photo_01.jpg, plus hero_photo_01-portrait.jpg
// for phones) and rerun the script, or let "prebuild" do it.

export type MediaImage = {
  src: string;
  width: number;
  height: number;
  /** 12 px JPEG, inlined as the placeholder while the real file streams in. */
  blurDataURL: string;
};

export type MediaEntry = MediaImage & {
  /** A 4:5 or taller export for portrait viewports, when the shoot supplied one. */
  portrait?: MediaImage;
};

export const MEDIA_MANIFEST: Record<string, MediaEntry> = {

};

export function mediaFor(slot: string): MediaEntry | undefined {
  return MEDIA_MANIFEST[slot.toUpperCase()];
}
